version: "3.8"
services:
  # prometheus:
  #   build: ./prometheus

  #   ports:
  #     - 9090:9090
  #   volumes:
  #     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  backend:
    build:
      context: ./backend-v2
      dockerfile: Dockerfile
    ports:
      - 5000:8080
  orders-service:
    build:
      context: ./orders-service
      dockerfile: Dockerfile
    ports:
      - 5001:8080
    depends_on:
      - backend
  tm-ui-v2:
    build:
      context: ./tm-ui-v2
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - orders-service
