version: "3.8"
services:
  monolith:
    build:
      context: ./monolith
      dockerfile: Dockerfile
    volumes:
      - ./data:/data:rw
    ports:
      - 8080:8080
      - 10001:10001
      - 6300:6300
