website_url: "http://localhost:8080/ticket-monster"
window_size: "1920x1080"

actions:
  - action: navigate
    target: Administration
    wait: 1

  - action: click-target
    target: a[href="#/Venues"]
    wait: 1

  - action: navigate
    target: Create

  - action: input
    target: Enter the Venue Name
    value: Test venue

  - action: select_dropdown
    target: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Boston_Symphony_Hall_from_the_south.jpg/800px-Boston_Symphony_Hall_from_the_south.jpg"
    wait: 1

  - action: input
    target: Enter the Venue Description
    value: Here is a description of our new venue

  - action: input
    target: Enter the Venue Capacity
    value: 1000

  - action: input
    target: Enter the Venue Street
    value: "20 Address Road"

  - action: input
    target: Enter the Venue City
    value: "Dublin"

  - action: input
    target: Enter the Venue Country
    value: "Ireland"

  - action: click-target
    target: button#saveVenue

  - action: click-target
    target: a[href="#/Events"]
    wait: 1

  - action: navigate
    target: Create

  - action: input
    target: Enter the Event Name
    value: Test venue

  - action: select_dropdown
    target: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Boston_Symphony_Hall_from_the_south.jpg/800px-Boston_Symphony_Hall_from_the_south.jpg"
    wait: 1

  - action: select_dropdown_by_xpath
    target: //*[@id="category"]
    value: "Comedy"
    wait: 1

  - action: input
    target: Enter the Event Description
    value: Here is a description of our new event

  - action: click-target
    target: button#saveEvent

  - action: click-target
    target: a[href="#/Venues"]
    wait: 1

  - action: click-target
    target: a[href="#/Venues/edit/6"]
    wait: 1

  - action: click-target
    target: button#deleteVenue

  - action: click-target
    target: a[href="#/Events"]
    wait: 1

  - action: click-target
    target: a#next
    wait: 1

  - action: click-target
    target: a[href="#/Events/edit/20"]
    wait: 1

  - action: click-target
    target: button#deleteEvent
    wait: 1
