website_url: "http://localhost:8080/"
window_size: "1920x1080"

actions:
  - action: click_by_xpath
    target: //*[@id="main-navbar"]/ul/li[2]/a
    wait: 5
    checkpoint: true

  - action: click_by_xpath
    target: //*[@id="search-owner-form"]/a
    wait: 2

  - action: input_rand_by_id
    target: "firstName"
    value: "John"
    wait: 1
    checkpoint: true

  - action: input_rand_by_id
    target: "lastName"
    value: "Dunne"
    wait: 1

  - action: input_rand_by_id
    target: "address"
    value: "20 Address road"
    wait: 1

  - action: input_by_id
    target: "city"
    value: "Dublin"
    wait: 1

  - action: input_by_id
    target: "telephone"
    value: "0000000000"
    wait: 1

  - action: click_by_xpath
    target: //*[@id="add-owner-form"]/div[2]/div/button
    wait: 2

  - action: click_by_xpath
    target: /html/body/div/div/a[2]
    wait: 2

  - action: input_rand_by_id
    target: "name"
    value: "Alfredo"
    wait: 1
    checkpoint: true

  - action: input_by_id
    target: "birthDate"
    value: "12/05/2020"
    wait: 1

  - action: select_random_dropdown_option_by_xpath
    target: '//*[@id="type"]'

  - action: click_by_xpath
    target: /html/body/div/div/form/div[2]/div/button
    wait: 2

  - action: click_by_xpath
    target: /html/body/div/div/a[2]
    wait: 2

  - action: input_rand_by_id
    target: "name"
    value: "Peebee"
    wait: 1
    checkpoint: true

  - action: input_by_id
    target: "birthDate"
    value: "12/05/2020"
    wait: 1

  - action: select_random_dropdown_option_by_xpath
    target: '//*[@id="type"]'

  - action: click_by_xpath
    target: /html/body/div/div/form/div[2]/div/button
    wait: 2

  - action: click_by_xpath
    target: /html/body/div/div/a[2]
    wait: 2

  - action: input_rand_by_id
    target: "name"
    value: "Finn"
    wait: 1
    checkpoint: true

  - action: input_by_id
    target: "birthDate"
    value: "12/05/2020"
    wait: 1

  - action: select_random_dropdown_option_by_xpath
    target: '//*[@id="type"]'

  - action: click_by_xpath
    target: /html/body/div/div/form/div[2]/div/button
    wait: 2

  - action: click_by_xpath
    target: /html/body/div/div/a[2]
    wait: 2

  - action: input_rand_by_id
    target: "name"
    value: "Emma"
    wait: 1
    checkpoint: true

  - action: input_by_id
    target: "birthDate"
    value: "12/05/2020"
    wait: 1

  - action: select_random_dropdown_option_by_xpath
    target: '//*[@id="type"]'

  - action: click_by_xpath
    target: /html/body/div/div/form/div[2]/div/button
    wait: 2

  - action: click_by_xpath
    target: /html/body/div/div/table[2]/tbody/tr[1]/td[2]/table/tbody/tr/td[1]/a
    wait: 2

  - action: input_rand_by_id
    target: "name"
    value: "Old man Alfredo"
    wait: 1
    checkpoint: true

  - action: click_by_xpath
    target: /html/body/div/div/form/div[2]/div/button
    wait: 2

  - action: click_by_xpath
    target: /html/body/div/div/table[2]/tbody/tr[2]/td[2]/table/tbody/tr/td[1]/a
    wait: 2

  - action: input_rand_by_id
    target: "name"
    value: "Peebee the queen"
    wait: 1
    checkpoint: true

  - action: click_by_xpath
    target: /html/body/div/div/form/div[2]/div/button
    wait: 2

  # - action: click_by_xpath
  #   target: //*[@id="main-navbar"]/ul/li[3]/a
  #   wait: 4

  # - action: click_by_xpath
  #   target: /html/body/div/div/div[1]/span[4]/a
  #   wait: 2

  # - action: click_by_xpath
  #   target: //*[@id="main-navbar"]/ul/li[2]/a
  #   wait: 2

  # - action: input_by_id
  #   target: "lastName"
  #   value: "Dunne"
  #   wait: 2

  # - action: click_by_xpath
  #   target: //*[@id="search-owner-form"]/div[2]/div/button
  #   wait: 2

  # - action: click_by_xpath
  #   target: //*[@id="owners"]/tbody/tr[1]/td[1]/a
  #   wait: 2

  # - action: click_by_xpath
  #   target: //*[@id="main-navbar"]/ul/li[1]/a
  #   wait: 2

  # - action: select_random_dropdown_option_by_xpath
  #   target: '//*[@id="mediaItem"]'

  # - action: input
  #   target: "Enter the Venue Description"
  #   value: "Venue Description"

  # - action: select_random_dropdown_option_by_xpath
  #   target: '//*[@id="sections"]'

  # - action: input
  #   target: "Enter the Venue Capacity"
  #   value: "300"

  # - action: input
  #   target: "Enter the Venue Street"
  #   value: "20 Address road"

  # - action: input
  #   target: "Enter the Venue City"
  #   value: "Dublin"

  # - action: input
  #   target: "Enter the Venue Country"
  #   value: "Ireland"

  # - action: click_by_xpath
  #   target: //*[@id="saveVenue"]
  #   wait: 1

  # - action: click_by_xpath
  #   target: /html/body/div[1]/div[3]/div/div[1]/nav/div/a[10]
  #   wait: 1
  #   checkpoint: true

  # - action: click_by_xpath
  #   target: //*[@id="Create"]
  #   wait: 1
  #   checkpoint: true

  # - action: input_rand
  #   target: "Enter the TicketCategory Description"
  #   value: "Student"

  # - action: click_by_xpath
  #   target: //*[@id="saveTicketCategory"]

  # - action: click_by_xpath
  #   target: /html/body/div[1]/div[3]/div/div[1]/nav/div/a[2]
  #   checkpoint: true

  # - action: click_by_xpath
  #   target: //*[@id="Create"]
  #   wait: 1
  #   checkpoint: true

  # - action: input_rand
  #   target: "Enter the Event Name"
  #   value: "Random Event "

  # - action: select_random_dropdown_option_by_xpath
  #   target: '//*[@id="mediaItem"]'

  # - action: select_random_dropdown_option_by_xpath
  #   target: '//*[@id="category"]'

  # - action: input_rand
  #   target: "Enter the Event Description"
  #   value: "Random Event Description"

  # - action: click_by_xpath
  #   target: //*[@id="saveEvent"]
  #   wait: 1

  # - action: click_by_xpath
  #   target: /html/body/div[1]/div[3]/div/div[1]/nav/div/a[8]
  #   checkpoint: true

  # - action: click_by_xpath
  #   target: //*[@id="Create"]
  #   wait: 1
  #   checkpoint: true

  # - action: select_random_dropdown_option_by_xpath
  #   target: '//*[@id="event"]'

  # - action: select_random_dropdown_option_by_xpath
  #   target: '//*[@id="performances"]'

  # - action: select_random_dropdown_option_by_xpath
  #   target: '//*[@id="venue"]'

  # - action: select_random_dropdown_option_by_xpath
  #   target: '//*[@id="ticketPrices"]'

  # - action: click_by_xpath
  #   target: //*[@id="saveShow"]
  #   wait: 1
